<?php
return [
    "STRIPE_PUBLISHABLE_KEY"=>env("STRIPE_PUBLISHABLE_KEY"),
    "STRIPE_SECRET_KEY"=>env("STRIPE_SECRET_KEY"),
    "STRIPE_SUBSCRIPTION_PRICE_ID"=>env("STRIPE_SUBSCRIPTION_PRICE_ID"),
    "STRIPE_TEST_CUSTOMER_ID"=>env("STRIPE_TEST_CUSTOMER_ID"),
    "STRIPE_TEST_PAYMENT_METHOD_ID"=>env("STRIPE_TEST_PAYMENT_METHOD_ID")
];